### ISSUE TITLE
Problem: The repository doesn't have a prettier config file

### ISSUE THREAD

**Issue by Dev-Doggo** [truflation/truflation-contracts#38]

**Comment by markholdex** [comment]
@Dev-Doggo the problem title does not describe a pain-point that the user is having. The title is very developer-oriented now and doesn't provide context for stakeholders on the problem. A better title would be `Problem: developers don't follow similar code style` which would indicate the pinpoint the users (developers) have and the solution for your problem would be implementing a library or documenting a standardized format that every developer can use. The PR should also be named appropriately to our Guidelines.

**Comment by Dev-Doggo** [comment]
> @Dev-Doggo the problem title does not describe a pain-point that the user is having. The title is very developer-oriented now and doesn't provide context for stakeholders on the problem. A better title would be `Problem: developers don't follow similar code style` which would indicate the pinpoint the users (developers) have and the solution for your problem would be implementing a library or documenting a standardized format that every developer can use. The PR should also be named appropriately to our Guidelines.

@markholdex The contracts already have consistent code style as they were all originally written by the same developer, this problem/pr was 
created to fix the incorrect formatting that's happened since due to the missing prettier configuration, documenting standardized code style wasn't in the scope here
